name: ClearChat
version: 2.1
main: me.aberdeener.clearchat.ClearChat
commands:
   clearchat:
      aliases: [cc]
      description: Clear yo chat B  
   ccmsgnoperm: 
      aliases: [ccmnp]
      description: Change the no permission message
   ccmsgcleared: 
      aliases: [ccmc]
      description: Change the success message